volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  mlruns:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus-data:/prometheus
    networks:
      - prometheus-network
    ports:
      - "9090:9090"
    user: "0"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./data/grafana-data:/var/lib/grafana
    networks:
      - prometheus-network
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ALLOW_EMBEDDING=true"
      - "GF_SECURITY_COOKIE_SECURE=true"
      - "GF_SECURITY_COOKIE_SAMESITE=none"
    user: "0"

  app:
    build: .
    image: somehowaimanage:latest
    container_name: app
    ports:
      - "8501:8501"
      - "8000:8000"
      - "5001:5001"
    depends_on:
      - grafana
      - prometheus
    volumes:
      - ./app:/usr/src/app
    networks:
      - prometheus-network
    user: "0"

  mlflow:
    image: somehowaimanage:latest
    container_name: mlflow
    command: ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"]
    networks:
      - prometheus-network
    ports:
      - "5000:5000"
    volumes:
      - ./app/mlruns:/mlruns
    user: "0"

networks:
  prometheus-network:
    driver: bridge


